Test: Test.mxml
	mxmlc -library-path+=../lib/flexunit-4.1.0-8-as3_4.1.0.16076.swc \
	-library-path+=../lib/flexunit-uilistener-4.1.0-8-4.1.0.16076.swc \
	-library-path+=../lib/flixel-2.35.swc \
	-source-path+=../src \
	Test.mxml
#-static-link-runtime-shared-libraries 
clean:
	rm -rf Test.swf *~
