Randomhack: Randomhack.as
	flexcompile.py /opt/flex/bin/fcsh \
	mxmlc -library-path+=../lib/flixel-2.35.swc \
	-static-link-runtime-shared-libraries Randomhack.as

run:
	flashplayerdebugger Randomhack.swf

clean:
	rm -rf Randomhack.swf *~
